### PR TITLE
Entity type

### PR DESCRIPTION
**Pull request by BreadAndRoses95**
Made regex entity not highlightabled in the user says rows. We may still need to color them automatically in the user says when someone add regex entity in the slot part. I've seen @dcalvom speaking of making an api endpoint to highlight entities in user says part, this could be a solution.

Plus, I think I should change entity creation page when regex is selected to only allow users to add a list of regexs (that will be saved inside the examples part of the entity object)? Maybe we could keep the synonyms to allow value and original regex as slots found?

### CODE REVIEW

**Comment by BreadAndRoses95** [comment]
Now it's possible to add synonyms of regex entities that will follow this behavior : if a synonym of a regex entity is matched, the corresponding slot.regexEntity.value is filled with the value of the entity (no the synonym) and the original with the original value which can be a synonym.

**Comment by wrathagom** [comment]
Working pretty well for me. I am having some weird alignment and console errors, but I'm going to rebuild my Docker images tomorrow to see if the problem isn't on my side.

@dcalvom would we want tests for the API side of things? I'm assuming yes.

**Comment by BreadAndRoses95** [comment]
Well nothing on my side except the
Failed to load resource: the server responded with a status of 404 (Not Found)
:7500/intent/1/postFormat Failed to load resource: the server responded with a status of 404 (Not Found)
But I think that was here before. Maybe we should highlight multiple different occurrences when isList (and only the last one as this is the one added in last in the entities list and will override the other) is selected and loop over multiple different occurences on the backend side to allow matching several times different values of the same entities.

**Comment by BreadAndRoses95** [comment]
All right all tests passed and I included what I described before, have a look on the tooltip message, I do not think this is very clear but had no imagination to fill it properly :-/

**Pull request merged**
