### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by mordebip**
Added additional fields to french translation

### CODE REVIEW

**Comment by mordebip** [comment]
i may have a problem with one of the elements translated

```
  negativeNotificationTemplate: {
    id: 'app.components.ConversationBar.negativeNotificationTemplate',
    defaultMessage: 'There was an error {action} your {instanceType}. {emoji}',
  },
  errorCopyingSayingTemplate: {
    id: 'app.components.ConversationBar.negativeNotificationTemplate',
    defaultMessage:
      'There was an error copying the utterance into your sayings. Please add it manually. {emoji}',
  },
  errorMessageTemplate: {
    id: 'app.components.ConversationBar.negativeNotificationTemplate',
    defaultMessage: '{error}. {emoji}',
  },
```

**Comment by dcalvom** [comment]
I will change the keys and push the changes on master

**Comment by dcalvom** [comment]
@mordebip could you please chick the values I added here https://github.com/samtecspg/articulate/commit/363f11a579de87c0d192f37517214a9280d9be5c

**Comment by mordebip** [comment]
ok i'm pulling and will update the translation
Thank you

**Pull request merged**
