### PR TITLE
Added french language to ui and api default languages

### PR DESCRIPTION
**Pull request by mordebip**

### CODE REVIEW

**Comment by mordebip** [comment]
There are still a lot of missing elements on the translation json files, will push an updated version of the json file, including all the missing fields

**Comment by wrathagom** [comment]
wow, thanks so much for this! Is it all ready then?

@dcalvom can you try to suck this one in sometime soon.

**Comment by dcalvom** [comment]
I'm working on it

**Comment by mordebip** [comment]
Yes it is, and i will make an other push including the last missing items i found.
but first i'm trying to figure out what is the issue with the sign up (await request.cookieAuth.set({ id: user.id, name: user.name, email: user.email });) and sign in (404)

**Pull request merged**
